#!/bin/sh

# Commonly used colors to make your shell scripts pop!
# This helper has no special requirements.

# shellcheck disable=SC2034

ESCAPE="\x1B"
RESET="${ESCAPE}[0m"
BOLD="${ESCAPE}[1m"
DIM="${ESCAPE}[2m"
UNDERLINED="${ESCAPE}[4m"
INVERTED="${ESCAPE}[7m"

CLR_DEFAULT="${ESCAPE}[39m"
CLR_BLACK="${ESCAPE}[30m"
CLR_BLUE="${ESCAPE}[34m"
CLR_CYAN="${ESCAPE}[36m"
CLR_MAGENTA="${ESCAPE}[35m"
CLR_GREEN="${ESCAPE}[32m"
CLR_RED="${ESCAPE}[31m"
CLR_WHITE="${ESCAPE}[97m"
CLR_YELLOW="${ESCAPE}[33m"
CLR_DK_GRAY="${ESCAPE}[90m"
CLR_LT_BLUE="${ESCAPE}[94m"
CLR_LT_CYAN="${ESCAPE}[96m"
CLR_LT_GRAY="${ESCAPE}[37m"
CLR_LT_GREEN="${ESCAPE}[92m"
CLR_LT_MAGENTA="${ESCAPE}[95m"
CLR_LT_RED="${ESCAPE}[91m"
CLR_LT_YELLOW="${ESCAPE}[93m"

BG_BLACK="${ESCAPE}[40m"
BG_BLUE="${ESCAPE}[44m"
BG_CYAN="${ESCAPE}[46m"
BG_GREEN="${ESCAPE}[42m"
BG_DEFAULT="${ESCAPE}[49m"
BG_MAGENTA="${ESCAPE}[45m"
BG_RED="${ESCAPE}[41m"
BG_YELLOW="${ESCAPE}[43m"
BG_WHITE="${ESCAPE}[107m"
BG_DK_GRAY="${ESCAPE}[100m"
BG_LT_BLUE="${ESCAPE}[104m"
BG_LT_CYAN="${ESCAPE}[106m"
BG_LT_RED="${ESCAPE}[101m"
BG_LT_GRAY="${ESCAPE}[47m"
BG_LT_GREEN="${ESCAPE}[102m"
BG_LT_MAGENTA="${ESCAPE}[105m"
BG_LT_YELLOW="${ESCAPE}[103m"
