#!/bin/sh

# load Colors helper
# shellcheck disable=SC1091
. ../colors.sh

echo
echo
echo "${BOLD}STYLES:${RESET}"
echo "  ${BOLD}BOLD${RESET}"
echo "  ${DIM}DIM${RESET}"
echo "  ${UNDERLINED}UNDERLINED${RESET}"
echo "  ${INVERTED}INVERTED${RESET}"

echo
echo
echo "${BOLD}FOREGROUND COLORS:${RESET}"
echo "  ${CLR_DEFAULT}CLR_DEFAULT${RESET}"
echo "  ${CLR_BLACK}CLR_BLACK${RESET}"
echo "  ${CLR_BLUE}CLR_BLUE${RESET}"
echo "  ${CLR_CYAN}CLR_CYAN${RESET}"
echo "  ${CLR_MAGENTA}CLR_MAGENTA${RESET}"
echo "  ${CLR_GREEN}CLR_GREEN${RESET}"
echo "  ${CLR_RED}CLR_RED${RESET}"
echo "  ${CLR_WHITE}CLR_WHITE${RESET}"
echo "  ${CLR_YELLOW}CLR_YELLOW${RESET}"
echo "  ${CLR_DK_GRAY}CLR_DK_GRAY${RESET}"
echo "  ${CLR_LT_BLUE}CLR_LT_BLUE${RESET}"
echo "  ${CLR_LT_CYAN}CLR_LT_CYAN${RESET}"
echo "  ${CLR_LT_GRAY}CLR_LT_GRAY${RESET}"
echo "  ${CLR_LT_GREEN}CLR_LT_GREEN${RESET}"
echo "  ${CLR_LT_MAGENTA}CLR_LT_MAGENTA${RESET}"
echo "  ${CLR_LT_RED}CLR_LT_RED${RESET}"
echo "  ${CLR_LT_YELLOW}CLR_LT_YELLOW${RESET}"

echo
echo
echo "${BOLD}BACKGROUND COLORS:${RESET}"
echo "  ${BG_BLACK}BG_BLACK${RESET}"
echo "  ${BG_BLUE}BG_BLUE${RESET}"
echo "  ${BG_CYAN}BG_CYAN${RESET}"
echo "  ${BG_GREEN}BG_GREEN${RESET}"
echo "  ${BG_DEFAULT}BG_DEFAULT${RESET}"
echo "  ${BG_MAGENTA}BG_MAGENTA${RESET}"
echo "  ${BG_RED}BG_RED${RESET}"
echo "  ${BG_YELLOW}BG_YELLOW${RESET}"
echo "  ${BG_WHITE}BG_WHITE${RESET}"
echo "  ${BG_DK_GRAY}BG_DK_GRAY${RESET}"
echo "  ${BG_LT_BLUE}BG_LT_BLUE${RESET}"
echo "  ${BG_LT_CYAN}BG_LT_CYAN${RESET}"
echo "  ${BG_LT_RED}BG_LT_RED${RESET}"
echo "  ${BG_LT_GRAY}BG_LT_GRAY${RESET}"
echo "  ${BG_LT_GREEN}BG_LT_GREEN${RESET}"
echo "  ${BG_LT_MAGENTA}BG_LT_MAGENTA${RESET}"
echo "  ${BG_LT_YELLOW}BG_LT_YELLOW${RESET}"
